version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 159753
    ports:
      - '5432:5432'

# docker-compose -f docker-compose.yml stop && docker-compose -f docker-compose.yml rm -f && docker system prune -f && docker volume prune -f && docker-compose -f docker-compose.yml pull && docker-compose -f docker-compose.yml up -d